### ISSUE TITLE
Django default signup commented

### ISSUE THREAD

**Issue by juliancantillo** [ekratia/ekratia#1]
The goal is only allow facebook signup for user verification but the signup is not well commented, use 

```
{% comment "Optional note" %}
    <p>Commented out text with {{ create_date|date:"c" }}</p>
{% endcomment %}
```

instead for comments

![image](https://cloud.githubusercontent.com/assets/1072454/7776404/568f612e-0080-11e5-8fbf-06fdc7eaf9ea.png)

**Comment by johnfelipe** [comment]
@juliancantillo can u share me your email?

**Comment by juliancantillo** [comment]
@johnfelipe I sent it to your github profile email

**Comment by andresgz** [comment]
It's not an issue anymore.
