### ISSUE TITLE
The border of the header is rounded and it looks strange by showing two white dots

### ISSUE THREAD

**Issue by torrenegra** [ekratia/ekratia#2]
![screen shot 2015-05-24 at 9 33 52 pm](https://cloud.githubusercontent.com/assets/1202646/7791860/a00b2fee-025c-11e5-988e-eea44dadd7ae.png)

**Comment by hecontreraso** [comment]
Fixed with commit 61. idekratia/static/css/project.css was modified.

**Comment by uxDaniel** [comment]
Thank you! BTW, rather sooner than later, we will merge all this CSS file (quick hacks during the hackaton) into the SASS files.

**Comment by torrenegra** [comment]
Thank you!

Alexander Torrenegra
CEO of Bunny Inc. http://bunnyinc.com
@torrenegra http://twitter.com/torrenegra
